### ISSUE TITLE
Improve performance

### ISSUE THREAD

**Issue by lpil** [JohnBjrk/gap#1]
Hello! Thanks again for this library, it has been very useful.

Over in the Exercism test runner we've hit a problem where large inputs would cause `gap` to take longer to complete than we have available. I'd really like to continue to use this package, so we'll have to make some performance improvements.

I've spent the morning trying to understand how we might improve the performance of the algorithm used, but it is beyond my understanding.

I looked into what Elixir does and they implement an algorithm from the paper "An O(ND) Difference Algorithm and Its Variations" by E. Myers. I benchmarked it with a 360 character string with a few randomly placed edits and it ran in 1/1950 the time with 1/570 the memory usage, even with a performance hit from not consolidating Elixir protocols.

Looking at the implementation it seems like it could be adapted to Gleam straightforwardly, perhaps we can ~~steal~~ follow their lead and use the same algorithm.

Cheers,
Louis

https://github.com/elixir-lang/elixir/blob/74bfab8ee271e53d24cb0012b5db1e2a931e0470/lib/elixir/lib/list.ex#L1047-L1174

**Comment by JohnBjrk** [comment]
Thanks for opening an issue and really nice to see that gap is useful. 

I also went back to look at the implementation to see what could be done in order to improve the performance and I really wish that I had written some more comments on the algorithm.

From your benchmarking it seems like a good idea to try to implement the algorithm from Elixirs to improve the performance of gap. I will give that a shot. 

/
John

**Comment by JohnBjrk** [comment]
@lpil Did you have an easy way to do the benchmarking that you could share?

Haven’t started to look into the Myers algorithm yet but it would be nice to have a way to compare any changes I make to the current performance.

**Comment by lpil** [comment]
Here's the code I used. You'll need to have Elixir installed to use it:

https://github.com/lpil/gap/commit/b2f14fffb2593736724326a35fd0f24faa6e88ca

**Comment by JohnBjrk** [comment]
@lpil Thanks for sharing the benchmarking code 🙏 

I'm still trying to figure out the Myers diff algorithm in order to implement it in gleam. Meanwhile I did some adjustments where any leading/trailing matches are omitted when running the diff. It's not close to as efficient as the Myers algorithm but gave an improvement of 1/7 in time and 1/6 in memory usage compared to the old implementation on the dataset from your benchmarks. Worst case is of course same as the for the old implementation but should help a bit on long string with similar starts or ends.

**Comment by JohnBjrk** [comment]
So version 0.6.0 didn't live very long ...
Now added Myers diff algorithm (adapted from Elixir). I used the version in Elixir 1.4 as a base (the newer version handled nested diffs which gap anyway doesn't support). This is published in version 0.7.0.

Benchmarks seemed promising (about 1/50 time and 1/20 memory compared to the optimised LCS version) so hopefully this can solve the timeout issues when running on Exercism.

**Comment by JohnBjrk** [comment]
Forgot to close this after the new algorithm was implemented.
